project_identifier: PROJECT_IDENTIFIER_CROWDIN
api_key: API_KEY_CROWDIN
base_path: ./
preserve_hierarchy: true
files:
  - source: /content/en/*.yaml
    translation: /content/%two_letters_code%/%original_file_name%
  - source: /content/en/*.md
    translation: /content/%two_letters_code%/%original_file_name%
    ignore:
      - /content/en/terms.md
      - /content/en/diversity_sep2020.md
  - source: /content/en/case-studies/*.md
    translation: /content/%two_letters_code%/case-studies/%original_file_name%
